### ISSUE TITLE
Mamba command not found

### ISSUE THREAD

**Issue by martinRenou** [QuantStack/mamba#34]
I installed `minimamba` and create a minimal `voila` environment. The issue is that from the base environment I have the mamba command available, but whenever I activate the `voila` environment `mamba` is not available anymore...

![mamba_trace](https://user-images.githubusercontent.com/21197331/59256102-85f29880-8c33-11e9-824a-fa4eda8ba7ed.png)

**Comment by wolfv** [comment]
yep, indeed we need to figure out how to make the `mamba` command available outside the base environment! Thanks for reporting.

**Comment by xyu** [comment]
This seems tricky because ideally we would want `mamba` to be in the user's PATH even when there is no active conda environment (post `conda deactivate`) as well so that `mamba env create ...` work regardless of which if any conda env is active. In our build process I'm just linking `mamba` to a bin dir which seems to work well:

```
ls -s "$(conda info --base)/bin/mamba" "/usr/local/bin/mamba"
```

**Comment by wolfv** [comment]
Actually there is another directory in the conda base environment called
‘condabin‘ which is where conda itself is adding a copy of the conda
executable to be available in all environments. I was planning to do the
same, but from the recipes build.sh

However, this would not work completely outside of conda.

**Comment by wolfv** [comment]
this is fixed for linux now -- need to confirm that it works on osx & win as well (win not yet released).

**Comment by sackh** [comment]
is this fixed for Windows? I am still getting this error.

**Comment by wolfv** [comment]
yep, should be fixed on windows, too.

What version do you have? Did you run `conda init`?

**Comment by sackh** [comment]
I am using the latest version. I did try conda init but still the same error.

**Comment by wolfv** [comment]
can you post `conda info` and the contents of your base env `condabin` folder?

**Comment by sackh** [comment]
sorry for the late reply. It is working now, after reinstall.

**Comment by Haydnspass** [comment]
@wolfv I believe that does not work when one does not have write access to condabin, correct? I am on a shared cluster environment where the base environment and packages in general are managed centrally.
I tried 
- updating mamba
- remove the env in which mamba was and reinstall
But it still does not work.


![image](https://user-images.githubusercontent.com/16120273/106015773-19a20280-60bf-11eb-8167-d445cf22e656.png)

**Comment by Haydnspass** [comment]
As a workaround adding `mamba() { ~/.conda/envs/base_mamba/bin/mamba "$@" ;}`to `~/.bashrc` does the trick though

**Comment by drahnreb** [comment]
for mambaforge on osx a simple `mamba() { ~/mambaforge/bin/mamba "$@" ;}` in `.zshrc` works too. tested on osx-arm64.

**Comment by connorads** [comment]
For anyone on macOS using Catalina or newer and thus have `zsh` instead of `bash`
`conda init zsh`

**Comment by the-rich-piana** [comment]
> As a workaround adding `mamba() { ~/.conda/envs/base_mamba/bin/mamba "$@" ;}`to `~/.bashrc` does the trick though

Where did you add this in bashrc? It says my base env is micromamba but I can't seem to run 'mamba' in the terminal anywhere. Strangely enough, all my packages and the environment is working fine and being recognized by VScode.

![image](https://user-images.githubusercontent.com/15808990/193106829-7b03330b-a275-4837-9078-fea42d93398b.png)

**Comment by foobar41** [comment]
I still cannot run mamba in another environment, runs only in base. Can anyone help ? Should I add to path environments or something ?

**Comment by jonashaag** [comment]
Please create a new ticket using the issue template and show exactly what you did and what you expected

**Comment by lucidBrot** [comment]
This is still an issue. Installing with mambaforge-pypy first runs into the [issue of missing DLLs](https://github.com/conda-forge/miniforge/issues/385#issuecomment-1552285097). After manually copying the files to the correct location, mamba works in the miniforge base env, but is not found in an environment created with `mamba create`.

My workaround for now is this:  
* create a folder somewhere and inside it a link to the `mamba.bat` from `mambaforge-pypy3\condabin\mamba.bat`
* add that folder to the path in the windows settings
* use `mamba.lnk` instead of `mamba` for all commands once the env is activated
