### ISSUE TITLE
Error creating environment from YML file

### ISSUE THREAD

**Issue by telatin** [QuantStack/mamba#41]
Trying to install Qiime 2.0 [https://qiime2.org] as from package instructions, but replacing "conda" with "mamba":
```bash
wget https://data.qiime2.org/distro/core/qiime2-2019.4-py36-linux-conda.yml
mamba env create -n qiime2-2019.4 --file qiime2-2019.4-py36-linux-conda.yml
```
will not work:
```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1003, in __call__
        return func(*args, **kwargs)
      File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda_env/cli/main.py", line 73, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 101, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/mamba/mamba_env.py", line 59, in mamba_install
        mamba_solve_specs, False, False)
    TypeError: solve(): incompatible function arguments. The following argument types are supported:
        1. (arg0: List[Tuple[str, str, int]], arg1: str, arg2: List[str], arg3: List[Tuple[int, int]], arg4: int, arg5: bool, arg6: bool) -> Tuple[List[Tuple[str, str, str]], List[Tuple[str, str]]]

    Invoked with: [('https://conda.anaconda.org/bioconda/noarch', '/home/ubuntu/miniconda3/pkgs/cache/2a957770.json', 12), ('https://repo.anaconda.com/pkgs/r/linux-64', '/home/ubuntu/miniconda3/pkgs/cache/2ce54b42.json', 9), ('https://conda.anaconda.org/conda-forge/noarch', '/home/ubuntu/miniconda3/pkgs/cache/09cdf8bf.json', 13), ('https://conda.anaconda.org/bioconda/linux-64', '/home/ubuntu/miniconda3/pkgs/cache/ffeee55f.json', 12), ('https://conda.anaconda.org/conda-forge/linux-64', '/home/ubuntu/miniconda3/pkgs/cache/497deca9.json', 13), ('https://repo.anaconda.com/pkgs/main/noarch', '/home/ubuntu/miniconda3/pkgs/cache/3e39a7aa.json', 11), ('https://repo.anaconda.com/pkgs/r/noarch', '/home/ubuntu/miniconda3/pkgs/cache/   {{ ...CUT... }} ', 'xorg-xextproto 7.3.0.*', 'xorg-xproto 7.0.31.*', 'xz 5.2.4.*', 'yaml 0.1.7.*', 'zeromq 4.3.1.*', 'zlib 1.2.11.*'], False, False

`$ /home/ubuntu/miniconda3/bin/mamba create -n qiime2-2019.4 --file qiime2-2019.4-py36-linux-conda.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
               CONDA_ROOT=/home/ubuntu/miniconda3
                 INFOPATH=/home/linuxbrew/.linuxbrew/share/info:
          LD_LIBRARY_PATH=:/usr/local/lib/
                  MANPATH=/home/linuxbrew/.linuxbrew/share/man:
               MODULEPATH=/etc/environment-modules/modules:/usr/share/modules/versions:/usr/Modu
                          les/$MODULE_VERSION/modulefiles:/usr/share/modules/modulefiles
                     PATH=/home/ubuntu/miniconda3/bin:/mnt/galaxy/tools/bin:/usr/lib/postgresql/
                          9.5/bin:/home/ubuntu/bin:/home/ubuntu/.local/bin:/home/ubuntu/minicond
                          a3/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:
                          /mnt/galaxy/tools/bin:/usr/lib/postgresql/9.5/bin:/usr/local/sbin:/usr
                          /local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/
                          snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/
                          bin:/usr/lib/jvm/java-8-oracle/jre/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /home/ubuntu/.condarc
 populated config files : /home/ubuntu/.condarc
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.6.7.final.0
       base environment : /home/ubuntu/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
          package cache : /home/ubuntu/miniconda3/pkgs
                          /home/ubuntu/.conda/pkgs
       envs directories : /home/ubuntu/miniconda3/envs
                          /home/ubuntu/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.18.4 CPython/3.6.7 Linux/4.4.0-134-generic ubuntu/16.04.3 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

I assume this is expected, but just wanted to supply an example of this kind of issues.

**Comment by wolfv** [comment]
Indeed there is a bug that I just fixed.

**Comment by telatin** [comment]
Thanks for the fix. I tried `conda update mamba`, i still get:
```
 >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1003, in __call__
        return func(*args, **kwargs)
      File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda_env/cli/main.py", line 73, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 101, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/mamba/mamba_env.py", line 59, in mamba_install
        mamba_solve_specs, False, False)
    TypeError: solve(): incompatible function arguments. The following argument types are supported:
        1. (arg0: List[Tuple[str, str, int]], arg1: str, arg2: List[str], arg3: List[Tuple[int, int]], arg4: int, arg5: bool, arg6: bool) -> Tuple[List[Tuple[str, str, str]], List[Tuple[str, str]]]
etc
```

To be fair I'm not sure I'm getting the right update: if `mamba --version` returns `conda 4.6.14`, is it the right way to check Mamba's version?

**Comment by mdehollander** [comment]
Same error here using conda 0.07 installed with conda:
```
$ conda list | grep mamba
mamba                     0.0.7            py37hc9558a2_1    conda-forge
```

**Comment by wolfv** [comment]
i need to do a release, sry!

**Comment by xyu** [comment]
Any timeline for pushing another release to `conda-forge` with 5ff168d391b02b24e689dccdaec2b91489fdb360?

**Comment by mdehollander** [comment]
Using the compiled version from master I still get an error installing the qiime software:

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "~/.conda/envs/mamba/lib/python3.7/site-packages/conda/exceptions.py", line 1003, in __call__
        return func(*args, **kwargs)
      File "~/.conda/envs/mamba/lib/python3.7/site-packages/conda_env/cli/main.py", line 73, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "~/.conda/envs/mamba/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 101, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "~/.conda/envs/mamba/lib/python3.7/site-packages/mamba/mamba_env.py", line 88, in mamba_install
        rec = to_package_record_from_subjson(sdir, pkg, jsn_s)
      File "~/.conda/envs/mamba/lib/python3.7/site-packages/mamba/utils.py", line 54, in to_package_record_from_subjson
        info = json.loads(jsn_string)
      File "~/.conda/envs/mamba/lib/python3.7/json/__init__.py", line 348, in loads
        return _default_decoder.decode(s)
      File "~/.conda/envs/mamba/lib/python3.7/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "~/.conda/envs/mamba/lib/python3.7/json/decoder.py", line 353, in raw_decode
        obj, end = self.scan_once(s, idx)
    json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 200 (char 199)
```

**Comment by wolfv** [comment]
hi @mdehollander thanks for checking. there seems to be another bug! I am looking into it.

**Comment by wolfv** [comment]
those two bugs are now fixed (also I've added travis so we don't run into this again in the future).

**Comment by wolfv** [comment]
https://travis-ci.com/wolfv/mamba

**Comment by mdehollander** [comment]
Great! It works for me now. Thanks.
